[project]
name = "python-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lab1" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
python-lab = "python_lab:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
